name: Deploy React Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: List directory contents
        run: ls -la

      - name: Install dependencies
        run: |
          npm install
          npm list vite react typescript @vitejs/plugin-react

      - name: Check TypeScript configuration
        run: |
          echo "TypeScript Config:"
          cat tsconfig.json
          echo "Node TypeScript Config:"
          cat tsconfig.node.json

      - name: Build
        env:
          REACT_APP_EMAILJS_SERVICE_ID: ${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}
          REACT_APP_EMAILJS_TEMPLATE_ID: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }}
          REACT_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.REACT_APP_EMAILJS_PUBLIC_KEY }}
        run: |
          echo "Starting build process..."
          npm run build --verbose
          echo "Build completed. Checking dist directory:"
          ls -la dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-app/dist
          force_orphan: true 